service: alerts

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  timeout: 5
  
#  stage: dev
  region: us-east-1
  environment:
        TABLE_NAME: alerts-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - Fn::GetAtt:
          - AlertsDynamoDbTable
          - Arn

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  getAlerts:
    handler: bin/getAlerts
    events:
      - http:
          path: alerts
          method: get
          cors: true
     
resources:
  Resources:    
    AlertsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S  
          - AttributeName: start
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: start
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'alerts-${opt:stage, self:provider.stage}'
